### ISSUE TITLE
Which versions are cuda and pytorch?

### ISSUE THREAD

**Issue by kambehmw** [stanfordnlp/web-elements#2]
When training with cuda 10.1 and latest pytorch 1.3.1, I get the following error.

```
Traceback (most recent call last):
  File "./main.py", line 87, in <module>
    run.train()
  File "/home/kambe/works/phrasenode/phrasenode/training_run.py", line 138, in train
    web_page_code, examples, train=True, logfile=self.logfile)
  File "/home/kambe/works/phrasenode/phrasenode/training_run.py", line 212, in _process_examples
    logits, losses, predictions = self.model(web_page, examples)
  File "/home/kambe/miniconda3/envs/py27-phrasenode/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kambe/works/phrasenode/phrasenode/model/encoding.py", line 151, in forward
    if not np.isfinite(losses.data.sum()):
  File "/home/kambe/miniconda3/envs/py27-phrasenode/lib/python2.7/site-packages/torch/tensor.py", line 449, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

Does it probably work with the following versions?

- cuda 9.0
- pytorch 1.1.0

please specify the details of the version in the readme file.

**Comment by ppasupat** [comment]
The code was developed on Pytorch 0.4.1 with CUDA 9. The information is now added to `README.md`.

For the error above, feel free to remove the offending `if not np.isfinite(...):` block. It should not be triggered if the loss is computed correctly.

**Comment by kambehmw** [comment]
Thank you for your quick response and telling me how to avoid this error.
I will try its workaround.
