### ISSUE TITLE
Tensor size mismatch when use_neighbors set to True

### ISSUE THREAD

**Issue by aburns4** [stanfordnlp/web-elements#8]
Hi, I am trying to run the embedding model with visual neighbors included, and run into a tensor size mismatch between the expected size of the score linear layer and the encoding input dimensions.

```
Training:   0%|          | 0/30000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./main.py", line 87, in <module>
    run.train()
  File "/research/aburns4/phrasenode/phrasenode/training_run.py", line 138, in train
    web_page_code, examples, train=True, logfile=self.logfile)
  File "/research/aburns4/phrasenode/phrasenode/training_run.py", line 212, in _process_examples
    logits, losses, predictions = self.model(web_page, examples)
  File "/scratch2/pnenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/research/aburns4/phrasenode/phrasenode/model/encoding.py", line 128, in forward
    scores = self.score(encoding)
  File "/scratch2/pnenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch2/pnenv/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/scratch2/pnenv/lib/python2.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [414 x 700], m2: [1100 x 1] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
```

I presume something might be wrong in the self.encode_dim calculation (such as the extra_nodes value) that's causing this. Any help would be appreciated! I am able to run the embedding model with use_neighbors set to False, as well as the alignment model with and without the visual neighbors. Thank you!

**Comment by ppasupat** [comment]
It looks like [`website.get_spatial_neighbors(...)`](https://github.com/stanfordnlp/phrasenode/blob/5be5363ac65e51b225c7179048bf9b3e71cd8319/phrasenode/webpage.py#L302) only grabs neighbors in 2 directions because [BELOW and RIGHT](https://github.com/stanfordnlp/phrasenode/blob/5be5363ac65e51b225c7179048bf9b3e71cd8319/phrasenode/webpage.py#L295) were commented out, while the [`neighbor_rels` in `EncodingModel`](https://github.com/stanfordnlp/phrasenode/blob/5be5363ac65e51b225c7179048bf9b3e71cd8319/phrasenode/model/encoding.py#L30) still lists all 4 directions. Uncommenting BELOW and RIGHT in `webpage.py` might solve the issue.

**Comment by aburns4** [comment]
That resolved the issue, thank you for the quick response!
